package jchrest.lib;

/**
 *
 * @author Martyn Lloyd-Kelly <martynlk@liverpool.ac.uk>
 */
public enum ChrestStatus {
  ACTION_NOT_IN_STM,
  ATTENTION_BUSY,
  COGNITION_BUSY,
  DISCRIMINATION_FAILED,
  DISCRIMINATION_SUCCESSFUL,
  FAMILIARISATION_FAILED,
  FAMILIARISATION_SUCCESSFUL,
  INPUT_ALREADY_LEARNED,
  LEARN_PRODUCTION_FAILED,
  LEARN_PRODUCTION_SUCCESSFUL,
  LEARNING_REFUSED,
  MODEL_DOES_NOT_EXIST_AT_TIME,
  NO_PRODUCTION_IDENTIFIED,
  PRODUCTION_ALREADY_LEARNED,
  PRODUCTION_REINFORCEMENT_FAILED,
  PRODUCTION_REINFORCEMENT_SUCCESSFUL,
  VISION_NOT_IN_STM
}
