package jchrest.lib;

/**
 *
 * @author Martyn Lloyd-Kelly <martynlk@liverpool.ac.uk>
 */
public enum ChrestStatus {
  ACTION_NOT_IN_STM,
  ATTENTION_BUSY,
  COGNITION_BUSY,
  DISCRIMINATION_FAILED,
  DISCRIMINATION_SUCCESSFUL,
  EXACT_PRODUCTION_LEARNED,
  EXACT_PRODUCTION_MATCH_REINFORCED,
  FAMILIARISATION_FAILED,
  FAMILIARISATION_SUCCESSFUL,
  FIXATION_SET_COMPLETE,
  FIXATION_SET_BEING_PERFORMED,
  HIGH_PRODUCTION_MATCH_REINFORCED,
  INPUT_ALREADY_LEARNED,
  LEARN_PRODUCTION_FAILED,
  LEARN_PRODUCTION_SUCCESSFUL,
  LEARNING_REFUSED,
  LOW_PRODUCTION_MATCH_REINFORCED,
  MODEL_DOES_NOT_EXIST_AT_TIME,
  MODERATE_PRODUCTION_MATCH_REINFORCED,
  NO_FIXATION_SET_BEING_PERFORMED,
  NO_PRODUCTION_IDENTIFIED,
  OVERGENERALISED_PRODUCTION_LEARNED,
  PRODUCTION_ALREADY_LEARNED,
  PRODUCTION_REINFORCEMENT_FAILED,
  VISION_NOT_IN_STM
}
